### ISSUE TITLE
orderService模块配置

### ISSUE THREAD

**Issue by wjxiu** [nageoffer/12306#1]
在services/order-service/src/main/resources/application.yaml文件
关于
```
rocketmq:
  name-server: 127.0.0.1:9876
```
改为
```
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: Order_Dev_Group # 必须指定group
```
要加上rocketmq.producer.group,不然就无法创建RocketMQTemplate。不知道作者有没有遇到这个问题？
